export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGOUT = "LOGOUT";
export const USER_DELETED = "USER_DELETED";

export const GET_TWEETS = "GET_TWEETS";
export const CREATE_TWEET = "CREATE_TWEET";
export const GET_USER_TWEETS = "GET_USER_TWEETS";
export const CLEAR_TWEETS = "CLEAR_TWEETS";
export const DELETE_TWEET = "DELETE_TWEET";
export const LIKE_TWEET = "LIKE_TWEET";

export const SET_ALERT = "SET_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SET_LOADING = "SET_LOADING";
export const CLEAR_LOADING = "CLEAR_LOADING";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_UPDATED = "PROFILE_UPDATED";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_FOLLOWED = "PROFILE_FOLLOWED";
export const PROFILE_UNFOLLOWED = "PROFILE_UNFOLLOWED";
export const FOLLOW_LOADED = "FOLLOW_LOADED";

export const COMMENTS_LOADED = "COMMENTS_LOADED";
export const COMMENT_CREATED = "COMMENT_CREATED";
export const COMMENT_DELETED = "COMMENT_DELETED";

export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_DISPOSED = "SOCKET_DISPOSED";

export const CHAT_TARGET_SET = "CHAT_TARGET_SET";
export const CHAT_TARGET_CLEARED = "CHAT_TARGET_CLEARED";
